type Book {
    id: ID!
    title: String!
    subtitle: String
    author: String!
    description: String!
    shortDescription: String!
    image: String
    price: Float!
    promotion: Float!
}

input FindBookCriteria {
    titleContains: String
}

extend type Query {
    findBooks(criteria: FindBookCriteria!, skip: Int, limit: Int): [Book]!
    findBookById(id: ID!): Book
    getBookPaginationMeta(criteria: FindBookCriteria!): PaginationMeta!
    getRandomBooks(limit: Int): [Book]!
    getDiscountedBooks(limit: Int): [Book]!
}

extend type Mutation {
    addBook(
        title: String!
        subtitle: String
        author: String!
        description: String!
        shortDescription: String!
        image: String!
        price: Float!
        promotion: Float
    ): Book!
    updateBook(
        id: ID!
        title: String
        subtitle: String
        author: String
        description: String
        shortDescription: String
        image: String
        price: Float
        promotion: Float
    ): Book!
    deleteBook(id: ID!): Book!
}
