type CartItem {
    id: ID!
    book: Book!
    quantity: Int!
}

type OrderItem {
    id: ID!
    book: Book!
    quantity: Int!
    pricePerItem: Float!
}

type Order {
    id: ID!
    orderItems: [OrderItem]!
    createdAt: Date!
}

extend type Mutation {
    addToCart(bookId: ID!): CartItem!
    removeFromCart(bookId: ID!): CartItem!
    checkout(password: String!): Order!
}
